[package]
name = "dynstack"
version = "0.1.0"
edition = "2021"
authors = ["sarah <>"]
description = "Dynamic stack wrapper for unsized allocations"
readme = "README.md"
repository = "https://github.com/kitegi/dynstack/"
license = "MIT"
keywords = ["stack", "allocation", "unsized", "array", "slice"]

[dependencies]
reborrow = "0.1.1"
